### ISSUE TITLE
import error (tools.addons.update)

### ISSUE THREAD

**Issue by mobyeno** [LimerBoy/Impulse#1]
http://c2n.me/45MXa4b
forgot to say that this problem is on Kali

**Comment by Rxltxn** [comment]
I have the same problem on Kali Linux

**Comment by makr2857** [comment]
i have this problem too

**Comment by VasyaDolmat1917** [comment]
I had the same problem, but i solved it using python 3

**Comment by Rxltxn** [comment]
> I had the same problem, but i solved it using python 3

How can I install python 3 on Kali?

**Comment by VasyaDolmat1917** [comment]
> > I had the same problem, but i solved it using python 3
> 
> How can I install python 3 on Kali?

apt install python3 
lol

**Comment by Rxltxn** [comment]
> > > I had the same problem, but i solved it using python 3
> > 
> > 
> > How can I install python 3 on Kali?
> 
> apt install python3
> lol

Oh, OK I will try it, ty

**Comment by VasyaDolmat1917** [comment]
> > > > I had the same problem, but i solved it using python 3
> > > 
> > > 
> > > How can I install python 3 on Kali?
> > 
> > 
> > apt install python3
> > lol
> 
> Oh, OK I will try it, ty

do not forget about package python3-pip, which you can launch pip3 instead of pip

**Comment by Rxltxn** [comment]
> > > > > I had the same problem, but i solved it using python 3
> > > > 
> > > > 
> > > > How can I install python 3 on Kali?
> > > 
> > > 
> > > apt install python3
> > > lol
> > 
> > 
> > Oh, OK I will try it, ty
> 
> do not forget about package python3-pip, which you can launch pip3 instead of pip

Everything is too complicated, I just recently started using Linux and even with Google it will be difficult for me to do this

**Comment by Salencore** [comment]
The problem remains relevant, installed Python 2.3 version. What can be done?

**Comment by R666H** [comment]
![Screenshot 2020-01-22 15^%46^%43](https://user-images.githubusercontent.com/59792040/73596993-34d84180-4541-11ea-824a-3f706d22f847.png)
 new problem

**Comment by R666H** [comment]
problem soved just:
 pip3 install wget

**Comment by R666H** [comment]
NO! nwe problem python impulse.py --method SMS --target +XXXXXXXXXXXX --time 20 --threads 2 and then we say same that in your pictures

**Comment by Salencore** [comment]
ERROR
ImportError: No Module named addons.update. HELP

**Comment by Salencore** [comment]
> ОШИБКА
> ImportError: Нет модуля с именем addons.update. ПОМОГИТЕ

Fix:
pip3 install 
sudo python3 impulse.py

**Comment by VasyaDolmat1917** [comment]
> ![Screenshot 2020-01-22 15^%46^%43](https://user-images.githubusercontent.com/59792040/73596993-34d84180-4541-11ea-824a-3f706d22f847.png)
> new problem

try 
pip3 install -r requirements.txt

**Comment by Rxltxn** [comment]
New problem, guys 
![image](https://user-images.githubusercontent.com/60547045/73598753-e0cf5c00-4544-11ea-863d-c5dd8ef64a01.png)

**Comment by LimerBoy** [comment]
> New problem, guys
> ![image](https://user-images.githubusercontent.com/60547045/73598753-e0cf5c00-4544-11ea-863d-c5dd8ef64a01.png)

Привет, мой ноутбук сломался и я не могу исправить этот баг сейчас. Попробуй открыть файл: impulse.py в текстовом редакторе и поставить знак '#' перед строкой 'import tools.addons.update'

**Comment by Rxltxn** [comment]
> > New problem, guys
> > ![image](https://user-images.githubusercontent.com/60547045/73598753-e0cf5c00-4544-11ea-863d-c5dd8ef64a01.png)
> 
> Привет, мой ноутбук сломался и я не могу исправить этот баг сейчас. Попробуй открыть файл: impulse.py в текстовом редакторе и поставить знак '#' перед строкой 'import tools.addons.update'

Сейчас попробую, надеюсь все заработает)

**Comment by Rxltxn** [comment]
> > New problem, guys
> > ![image](https://user-images.githubusercontent.com/60547045/73598753-e0cf5c00-4544-11ea-863d-c5dd8ef64a01.png)
> 
> Привет, мой ноутбук сломался и я не могу исправить этот баг сейчас. Попробуй открыть файл: impulse.py в текстовом редакторе и поставить знак '#' перед строкой 'import tools.addons.update'

Отлично, все заработало! Теперь осталось понять как флудить звонками)

**Comment by LimerBoy** [comment]
> > > New problem, guys
> > > ![image](https://user-images.githubusercontent.com/60547045/73598753-e0cf5c00-4544-11ea-863d-c5dd8ef64a01.png)
> > 
> > 
> > Привет, мой ноутбук сломался и я не могу исправить этот баг сейчас. Попробуй открыть файл: impulse.py в текстовом редакторе и поставить знак '#' перед строкой 'import tools.addons.update'
> 
> Отлично, все заработало! Теперь осталось понять как флудить звонками)

В файле readme в низу есть пример.
