### ISSUE TITLE
ImportError: No module named tools.SMS.main

### ISSUE THREAD

**Issue by VoronRV** [LimerBoy/Impulse#11]
Hi
i'm getting this error when i start the impulse.py

Failed import some modules
Traceback (most recent call last):
  File "impulse.py", line 75, in <module>
    main()
  File "impulse.py", line 68, in main
    from tools.SMS.main import SMS_ATTACK
ImportError: No module named tools.SMS.main

Cloned all the files still getting this error..

No works from powershell...

**Comment by VoronRV** [comment]
Да и с остальными модулями такая же хреновина...

**Comment by LimerBoy** [comment]
Попробуй с главной папки запустить

**Comment by VoronRV** [comment]
что за главная папка?

**Comment by VoronRV** [comment]
C:\> cd C:\Impulse-master
C:\Impulse-master> python impulse.py --method SMS --target +XXXXXXXXXXX --time 20 --threads 2
Failed import some modules
Traceback (most recent call last):
  File "impulse.py", line 74, in <module>
    main()
  File "impulse.py", line 67, in main
    from tools.SMS.main import SMS_ATTACK
ImportError: No module named tools.SMS.main
C:\Impulse-master>

**Comment by LimerBoy** [comment]
Попробуй скачать новую версию

**Comment by VoronRV** [comment]
Заработало, проблема была в версии питона (2.7.10) и PIP
