### ISSUE TITLE
Pls help me: No module named tools.SMS.main

### ISSUE THREAD

**Issue by phanthuthao** [LimerBoy/Impulse#12]
Failed import some modules :/
Traceback (most recent call last):
  File "impulse.py", line 79, in <module>
    main()
  File "impulse.py", line 72, in main
    from tools.SMS.main import SMS_ATTACK
ImportError: No module named tools.SMS.main

**Comment by Ranjithkumar567** [comment]
Same problem here also

**Comment by LimerBoy** [comment]
Try start from windows powershell

**Comment by Ranjithkumar567** [comment]
> 
> 
> Try start from windows powershell

pip not working in windows powershell

**Comment by LimerBoy** [comment]
install python 3.7
click "Add python to path"

**Comment by LimerBoy** [comment]
Use python 3.8
