### ISSUE TITLE
SMS test error

### ISSUE THREAD

**Issue by DarkReitor** [LimerBoy/Impulse#13]
Error when trying to use SMS module
![image](https://user-images.githubusercontent.com/45410348/80119170-f4d89780-854e-11ea-9dbe-93d010d82284.png)

**Comment by LimerBoy** [comment]
What python version you use?

**Comment by beavis-mx** [comment]
similar problem:
Failed import some modules :/

**Comment by DarkReitor** [comment]
> What python version you use?

The one that your recommend in the readme. BTW, im running it on linux (in case that wasn't clear)

**Comment by KielVoid** [comment]
same error here

**Comment by Aamonpanthi** [comment]
same error also here
Failed import some modules :/

**Comment by DarkReitor** [comment]
> What python version you use?

I tried your new version and what I get is "Failed import some modules :/" only that but, I tried launching your last version usign python3 and the program actually lunch but with an error "Failed import some modules :/" but it actually works for me

**Comment by JmNkS** [comment]
i got the same program, finnally it works successful with python3.

**Comment by beavis-mx** [comment]
Python 3.6.9

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jDHFLa/wget/t'

**Comment by beavis-mx** [comment]
in windows works fine !

**Comment by game-lover** [comment]
Have you tried to use 'pip3 install -r requirements.txt' instead of 'pip install -r requirements.txt'?

**Comment by LimerBoy** [comment]
Use python3 and pip3 when installing requirements
