### ISSUE TITLE
Failed import some modules :/

### ISSUE THREAD

**Issue by protonwebmaster** [LimerBoy/Impulse#16]
I have an error after this command : `python3 impulse.py --help`
`Failed import some modules :/`
All requirements are satisfied.
It comes from these addons, how to solve this ?
   ```
    import tools.addons.clean
    import tools.addons.winpcap
    import tools.addons.logo
```

**Comment by game-lover** [comment]
Have you tried to use 'pip3 install -r requirements.txt' instead of 'pip install -r requirements.txt'?

**Comment by DgigolaD** [comment]
if pip install -r requirements.txt didnt work then type "sudo pip install -r requirements.txt"
or sudo pip3 install -r requirements.txt
