### ISSUE TITLE
i got it wrking but this?

### ISSUE THREAD

**Issue by logopogo1231** [LimerBoy/Impulse#19]
pip install -r requirements.txt
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pip install -r requirements.txt
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DgigolaD** [comment]
write pip3 install -r requirments.txt if that didnt work u ca use sudo pip3 install -r requirements.txt

**Comment by PinkDev1** [comment]
Make sure you have pip and python installed.
Also, make sure python is added to your PATH

**Comment by enty8080** [comment]
* Linux
`python3 -m pip install -r requirements.txt`

* Windows (do not use windows)
`py -m pip install -r requirements.txt`
