### ISSUE TITLE
Errno 13 in Termux Using Memcached attack type

### ISSUE THREAD

**Issue by onix-x** [LimerBoy/Impulse#22]

**Comment by PinkDev1** [comment]
Please attach error log

**Comment by onix-x** [comment]
> Please attach error log

How do you get it?

**Comment by LimerBoy** [comment]
> > Please attach error log
> 
> How do you get it?

Try downloading again, I updated and fixed many bugs. And don't forget to use python 3.

**Comment by onix-x** [comment]
> > > Please attach error log
> > 
> > How do you get it?
> 
> Try downloading again, I updated and fixed many bugs. And don't forget to use python 3.8

It really works! But only 50%

**Comment by LimerBoy** [comment]
> > > > Please attach error log
> > > 
> > > 
> > > How do you get it?
> > 
> > 
> > Try downloading again, I updated and fixed many bugs. And don't forget to use python 3.8
> 
> It really works! But only 50%

?????
