### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by ovhxyz** [LimerBoy/Impulse#25]
python3 impulse.py
Traceback (most recent call last):
  File "impulse.py", line 11, in <module>
    from tools.crash import CriticalError
  File "/root/Impulse/tools/crash.py", line 34
    """
      ^
SyntaxError: invalid syntax

**Comment by LimerBoy** [comment]
Download again, I made a couple of changes, if the problem persists then show the output of the command: python --version

**Comment by ovhxyz** [comment]
ight

**Comment by ovhxyz** [comment]
i figured out the problem
Python 3.5.3

**Comment by LimerBoy** [comment]
Install python 3.8

**Comment by ovhxyz** [comment]
yep fixed it

**Comment by ovhxyz** [comment]
Btw to the pod attack the max u can send it 65507 bytes

**Comment by LimerBoy** [comment]
> Btw to the pod attack the max u can send it 65507 bytes

ok i will change this in the next update
