### ISSUE TITLE
impulse.py: error: unrecognized arguments: 

### ISSUE THREAD

**Issue by wildfirebill** [LimerBoy/Impulse#26]
![Screenshot from 2020-05-28 18-14-56](https://user-images.githubusercontent.com/8473557/83200025-64264600-a110-11ea-98f6-c0313470be33.png)
I blacked out the number for security reasons. I ran one test so far and got this error in screenshot.

**Comment by LimerBoy** [comment]
Hi, show me what you entered in the terminal

**Comment by wildfirebill** [comment]
python3 impulse.py +13XXXXXXXXX--method SMS --time 5 --threads 10

**Comment by wildfirebill** [comment]
Also forgot to mention running Ubuntu 20.04 LTS

**Comment by LimerBoy** [comment]
python3 impulse.py **--target** +13XXXXXXXXX --method SMS --time 5 --threads 10
