### ISSUE TITLE
languages 

### ISSUE THREAD

**Issue by Fawazalenezii** [LimerBoy/Impulse#29]
hi 
how can I write the attacking email's subject in another language? 
every time I write in Arabic to send the email I got errors

**Comment by LimerBoy** [comment]
Plz sent error log

**Comment by Fawazalenezii** [comment]
Error while sending mail
'ascii' codec can't encode characters in position 42-46: ordinal not in range(128) 


^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:

**Comment by LimerBoy** [comment]
I fixed it. Please download new version.

> Error while sending mail
> 'ascii' codec can't encode characters in position 42-46: ordinal not in range(128)
> 
> ^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
> Traceback (most recent call last):
> File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
> lock.acquire()
> KeyboardInterrupt:
