### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by SaulCJ18** [LimerBoy/Impulse#30]
I think I don't know how to use it, but no command allows me to access the git

**Comment by Rang0ku** [comment]
> 
> 
> I think I don't know how to use it, but no command allows me to access the git

take a screenshot!

**Comment by lilcsz** [comment]
@SaulCJ18 Send screenshot or error code

**Comment by SaulCJ18** [comment]
I already solved it, thanks

**Comment by Mrxwai** [comment]
> 
> 
> I already solved it, thanks

how did u solved error my friend , please could you explain it ?
