### ISSUE TITLE
Not working on 3.5.3 Python Shell Server

### ISSUE THREAD

**Issue by lilcsz** [LimerBoy/Impulse#31]
lilcsz@xshellz-free:~$ clear
lilcsz@xshellz-free:~$ git clone https://github.com/LimerBoy/Impulse
Cloning into 'Impulse'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 393 (delta 16), reused 6 (delta 1), pack-reused 330
Receiving objects: 100% (393/393), 671.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (204/204), done.
lilcsz@xshellz-free:~$ chmod +x Impulse
lilcsz@xshellz-free:~$ chmod 777 * Impulse
lilcsz@xshellz-free:~$ ls Impulse
impulse.py  LICENSE  README.md  requirements.txt  tools
lilcsz@xshellz-free:~$ python3 impulse.py
python3: can't open file 'impulse.py': [Errno 2] No such file or directory
lilcsz@xshellz-free:~$ cd Impulse
lilcsz@xshellz-free:~/Impulse$ ls
impulse.py  LICENSE  README.md  requirements.txt  tools
lilcsz@xshellz-free:~/Impulse$ python3 impulse.py
Traceback (most recent call last):
  File "impulse.py", line 11, in <module>
    from tools.crash import CriticalError
  File "/home/l/lilcsz/Impulse/tools/crash.py", line 34
    """)
      ^
SyntaxError: invalid syntax
lilcsz@xshellz-free:~/Impulse$

**Comment by LimerBoy** [comment]
Use python 3.8

**Comment by lilcsz** [comment]
ok thx
