### ISSUE TITLE
Бот нет внутри спамера, что за?

### ISSUE THREAD

**Issue by mishailovic** [LimerBoy/Impulse#33]
Приветик ламер бой, настал момент расставить все по местам. Мы - разработчики из Snake programmers Inc. Подаём коллективную жалобу на репозиторий. Ор в том что тебя детектили уже, и ты даже коммиты не потер, биг Брейн тайм короче. Пруфы засринены и отправлены на архив.орг Жди звонка короче, тебя предупредили. 
![20200612_120838](https://user-images.githubusercontent.com/41520056/84486066-88a02780-aca5-11ea-86bd-ed7adfd3d4b9.jpg)
![20200612_120842](https://user-images.githubusercontent.com/41520056/84486069-8b028180-aca5-11ea-9231-4b84557dfd14.jpg)
![20200612_120844](https://user-images.githubusercontent.com/41520056/84486070-8b028180-aca5-11ea-82d5-05cf446439e3.jpg)

**Comment by y9san9** [comment]
Подтверждаю

**Comment by mishailovic** [comment]
Рассылать ратники через опен сорс программу под  GPL-3.0 лицензией это ну конечно новый виток в хакерских технологиях

**Comment by LimerBoy** [comment]
Малвари тут уже давно нету.

**Comment by y9san9** [comment]
Энивей возможность выполнять кастомный код на устройстве - опасно

**Comment by mishailovic** [comment]
![20200612_141148](https://user-images.githubusercontent.com/41520056/84497019-acb83480-acb6-11ea-9da5-79963e19b947.jpg)

**Comment by LimerBoy** [comment]
Код открытый, там ничего сейчас нету

**Comment by mishailovic** [comment]
> Код открытый, там ничего сейчас нету

https://t.me/b0mb3r4at/169353
https://t.me/b0mb3r4at/169362

Читай, чел заражался от твоей проги

**Comment by mishailovic** [comment]
Каковы шансы того что сейчас у людей не остались ратники? Пускай ты и удалил тот кусок кода (к сведению историю коммитов очень легко посмотреть, гитхаб хранит все что ему попало в руки)

**Comment by y9san9** [comment]
Пиши извинения в ридми для пользователей с какой-то версии и проси провериться антивирусом

**Comment by mishailovic** [comment]
Использовать юзеров, даже писать аналитику, это уже очень плохо

**Comment by mashed-potatoes** [comment]
_«однажды лаймербой застрелил человека.
через неделю к нему приехали менты. стучат, говорят открыть дверь
он открывает дверь, ему заламывают руки и зачитывают его нарушение - убийство
лаймербой говорит "Трупа тут уже давно нету."
полицейские извиняются и уходят»_

(с) [crinny](https://github.com/crinny)

**Comment by y9san9** [comment]
УК РФ Статья 273. Создание, использование и распространение вредоносных компьютерных программ

1. Создание, распространение или использование компьютерных программ либо иной компьютерной информации, заведомо предназначенных для несанкционированного уничтожения, блокирования, модификации, копирования компьютерной информации или нейтрализации средств защиты компьютерной информации, -
наказываются ограничением свободы на срок до четырех лет, либо принудительными работами на срок до четырех лет, либо лишением свободы на тот же срок со штрафом в размере до двухсот тысяч рублей или в размере заработной платы или иного дохода осужденного за период до восемнадцати месяцев.
