### ISSUE TITLE
СОБИРАЕТ ВСЮ ИНФУ О ВАС. Удаляйте!

### ISSUE THREAD

**Issue by Artem450-ss** [LimerBoy/Impulse#34]
Пидор, всю инфу пиздит. Даже банковские карты! Если у вас установлен Impulse, срочно удаляйте!! И вообще, ничего не качайте от LimerBoy'a!

**Comment by LimerBoy** [comment]
Малвари тут уже давно нету.

**Comment by catofsof** [comment]
но была же) не стыдно?)

**Comment by LimerBoy** [comment]
Нет, она была нужна для слива скамера и все.

**Comment by catofsof** [comment]
пытался слить одного человека, а слил нескольких) это типа случайно получилось?)
