### ISSUE TITLE
"Failed import some modules"

### ISSUE THREAD

**Issue by malorechka** [LimerBoy/Impulse#4]
New problem, after add 3 (#3, closed) i see this:
![2CF3B588-7498-4DB4-A507-2E46DF548EA4](https://user-images.githubusercontent.com/44815564/73607424-ec636700-45c6-11ea-983e-b43f484e4f3b.jpeg)

**Comment by LimerBoy** [comment]
In terminal: pip3 install -r requirements.txt

**Comment by malorechka** [comment]
> **In terminal run this commands:**
> 
> * sudo apt install python3-pip
> * pip3 install -r requirements.txt

Again..
![A5039921-5D14-4169-B7CE-AA4819AEDEA6](https://user-images.githubusercontent.com/44815564/73607861-ca6ce300-45cc-11ea-914d-6ccbbcb3c853.jpeg)
![4C48B6AD-F9C9-457B-BDC0-9E5CDC4523FA](https://user-images.githubusercontent.com/44815564/73607862-ca6ce300-45cc-11ea-9f57-cbd5050be317.jpeg)

**Comment by LimerBoy** [comment]
Try pip3 install phonenumbers

**Comment by malorechka** [comment]
> Try pip3 install phonenumbers

Ready, and again this problem..

**Comment by LimerBoy** [comment]
Okay.. Try delete you python and install version 3.6 | Or run on windows

**Comment by malorechka** [comment]
> Okay.. Try delete you python and install version 3.6 | Or run on windows

Ok)) Thanks)
