### ISSUE TITLE
Малварь!!!

### ISSUE THREAD

**Issue by ghost** [LimerBoy/Impulse#40]
В репозитории малварь! Да будет вам известно, что гитхаб хранит всю историю коммитов!!!!
Объясни пожалуйста цель внедрения вируса.

**Comment by LimerBoy** [comment]
Привет, я знаю что гитхаб хранит, вирус был предназначен для человека который продавал эту программу без моего ведома, я его наказал и ботнета больше нету, хватит уже создавать новые issues..

**Comment by cutekartoshka** [comment]
Допустим я тебе поверил, но ты всё таки не прав. Пиши в ридми просьбу чтобы юзеры проверились антивирусом.

И вообще насколько я вижу, так скамер слить твоим типом вируса невозможно (почти). Какой дурак будет хранить адреса ботнета или прочие штуки, связанные с ним на устройстве без пароля??? (Я имею ввиду зашифрованный архив)

Все же не похоже на правду...
