### ISSUE TITLE
Sms spam not wotking after updating the script

### ISSUE THREAD

**Issue by dragos-olaru** [LimerBoy/Impulse#42]
:=== Critical error:                                    MESSAGE: Failed import some modules.                    ERROR: No module named 'pyfiglet'                       :=== Python info:                                       PYTHON VERSION: 3.8.3                                   PYTHON BUILD: default, DATE: May 14 2020 14:40:29
    PYTHON COMPILER: Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6                 SCRIPT LOCATION: /data/data/com.termux/files/home/Impulse                                                       CURRENT LOCATION: /data/data/com.termux/files/home/Impulse                                                      :=== System info:                                       SYSTEM: Linux                                           RELEASE: 4.14.113-18731944                              VERSION: #1 SMP PREEMPT Wed Jun 3 12:19:58 KST 2020     ARCHITECTURE: 64bit                                     PROCESSOR:                                              MACHINE: aarch64                                        NODE: localhost
    TIME: Mon Jun 29 11:18:36 2020
    :=== Report:
    Please report it here: https://github.com/LimerBoy/Impulse/issues/new

**Comment by LimerBoy** [comment]
pip3 install -r requirements.txt

**Comment by dragos-olaru** [comment]
It's working! Thanks!

**Comment by shvx** [comment]
SyntaxError: invalid syntax
root@andrey:~/Impulse# python3 impulse.py
Traceback (most recent call last):
  File "impulse.py", line 11, in <module>
    from tools.crash import CriticalError
  File "/root/Impulse/tools/crash.py", line 34
    """);
      ^

Друг в чем проблема ? все поставил! 
Python 3.4.2

**Comment by LimerBoy** [comment]
Поставь питон 3.8
