### ISSUE TITLE
How to add more services

### ISSUE THREAD

**Issue by dragos-olaru** [LimerBoy/Impulse#43]
How did you get the urls?
Like this ones:
		{
			"url": "https://www.citilink.ru/registration/confirm/phone/+%phone%/"
		},
		{
			"url": "https://www.sportmaster.ua/?module=users&action=SendSMSReg&phone=+%phone%"
		},
		{
			"url": "https://www.oyorooms.com/api/pwa/generateotp?phone=+%phone%&country_code=%2B7&nod=4&locale=en"
		}

I want to get more urls and send them to you if you want.

**Comment by LimerBoy** [comment]
Hello, 
**How to find services:** https://youtu.be/WWcgR7k8a5w?t=24
**This lines will be replaced in the request:**
%phone% to target phone number
%name% to random name
%email% to random email
%password% to random password

**Example POST request:**
_{
    "url": "https://mos.pizza/bitrix/components/custom/callback/templates/.default/ajax.php",
    "data": "{'phone':'%phone%','name':'%name%'}"
}_
**Example GET request with params:**
_{
    "url": "https://prod.tvh.mts.ru/tvh-public-api-gateway/public/rest/general/send-code?msisdn=%phone%"
}_

.

**Comment by dragos-olaru** [comment]
I still don't understand. I know how to get the URL with chrome but how do i get the phone part. For exemple oyo rooms. It's just an url and it doesn't contain the phone number. The number is listed somewhere else. Can you make a video in english and explain how to do it?

**Comment by dragos-olaru** [comment]
How do i put that data that contains the phone number în the URL to look like this: https://WEBSITE.com/things/phone-number-here

**Comment by LimerBoy** [comment]
I can't make video because i am from Ukraine. I don't speak english :D

**Comment by dragos-olaru** [comment]
Ok. So i can get the URLs and put them in your script and run it?

**Comment by dragos-olaru** [comment]
Hello! Why is this not working? I'm from Romania and my country code is +40
{
	"services": [
	    {
			"url": "https://www.oyorooms.com/api/pwa/generateotp?locale=en",
			"data": "{'phone':'%phone%','country_code':'+40','nod':'4'}"
		}
	]
}
