### ISSUE TITLE
I use Kali Linux... Whats happend??

### ISSUE THREAD

**Issue by Buckethead65** [LimerBoy/Impulse#45]
-------------------------------------------
 ___                       _          
|_ _|_ __ ___  _ __  _   _| |___  ___ 
 | || '_ ` _ \| '_ \| | | | / __|/ _ \
 | || | | | | | |_) | |_| | \__ \  __/
|___|_| |_| |_| .__/ \__,_|_|___/\___|
              |_|                     

--------------------------------------------

    :=== Critical error:
    MESSAGE: Failed import some modules.
    ERROR: No module named 'humanfriendly'
    :=== Python info:
    PYTHON VERSION: 3.8.3
    PYTHON BUILD: default, DATE: May 14 2020 11:03:12
    PYTHON COMPILER: GCC 9.3.0
    SCRIPT LOCATION: /home/juanrozo/Impulse
    CURRENT LOCATION: /home/juanrozo/Impulse
    :=== System info:
    SYSTEM: Linux
    RELEASE: 5.7.0-kali1-amd64
    VERSION: #1 SMP Debian 5.7.6-1kali2 (2020-07-01)
    ARCHITECTURE: 64bit ELF
    PROCESSOR: 
    MACHINE: x86_64
    NODE: kali
    TIME: Sat Jul 11 04:22:05 2020                                         
    :=== Report:                                                           
    Please report it here: https://github.com/LimerBoy/Impulse/issues/new

**Comment by dragos-olaru** [comment]
pip3 install -r requirements.txt

**Comment by Buckethead65** [comment]
> pip3 install -r requirements.txt

i found the issue 1 hour later... i had not installed "humanfriendly" repository

daaa... the error said it hahaha
thank you for answering!!

**Comment by dragos-olaru** [comment]
👍
