### ISSUE TITLE
failed import modules

### ISSUE THREAD

**Issue by Snakuser** [LimerBoy/Impulse#5]
Hello! Tnx you for this code. But i have some issues. Can you help me?
![Screenshot_1](https://user-images.githubusercontent.com/60671568/73783868-7b2dda80-47a5-11ea-9625-e41eab226f17.png)

**Comment by Snakuser** [comment]
Sorry I didnt notice closed issues

**Comment by Snakuser** [comment]
Пробую на консоли W10 LTSC
Может ли быть дело в pip?

**Comment by LimerBoy** [comment]
Может проблем в версии питона, попробуй 3.6 у меня он.

**Comment by Snakuser** [comment]
> Может проблема в версии питона, попробуй 3.6 у меня он.

Да, я тоже думал об этом, поэтому переустановил питон, 3.6. стоит, но проблема не уходит. Больше нет догадок что это может быть?
Спасибо за ответ!

**Comment by LimerBoy** [comment]
Попробуй перестановить Impulse

**Comment by Snakuser** [comment]
Привет! Объясни пожалуйста по поводу потоков и звонков.
От количества потоков зависит частота сообщений и звонков? На что вообще влияют потоки?
В описании у тебя прописано "SMS & CALL FLOOD". Через какие сервисы происходят звонки и можно ли настроить флуд только звонками или только смс?

**Comment by LimerBoy** [comment]
Потоки влияют на сколько много запустить циклов отправки, сервисы в файле services.json
