### ISSUE TITLE
Commands doesnt work 

### ISSUE THREAD

**Issue by GTRacing65** [LimerBoy/Impulse#50]
CMD/PowerShell keeps says it cannot find h or --help etc none of the commands work i can start Impulse with CMD and PowerShell but all commands dont work

**Comment by dragos-olaru** [comment]
Show logs

**Comment by GTRacing65** [comment]
how?

**Comment by dragos-olaru** [comment]
Show me what commands did you type and copy paste what appears in your terminal

**Comment by GTRacing65** [comment]
![Unbenannt](https://user-images.githubusercontent.com/68713948/88407051-d2fee300-cdd1-11ea-911a-1e13c1327a82.png)

**Comment by GTRacing65** [comment]
The command " " is either misspelled or
could not be found

**Comment by dragos-olaru** [comment]
python3 impulse.py -h

**Comment by dragos-olaru** [comment]
not just "-h"

**Comment by GTRacing65** [comment]
still doesnt work nothing happens if i tip python3 impulse.py -h --target <IP>

**Comment by dragos-olaru** [comment]
No, not like that!
use this command: python3 inpulse.py --time TIME --threads THREADS --method METHOD --target TARGET
use python3 impulse.py -h to see the options.

**Comment by GTRacing65** [comment]
python impulse.py --time 2000 --threads 150 --method SYN --target 198.168.0.100  (python not python3) but know it says that i must enter a ip and a port but when a put 198.168.0.100 80 198.168.0.100 80 it keep says error: unrecognized arguments i tryed with 80, Port 80 and Port: 80

**Comment by dragos-olaru** [comment]
Don't put space between ip and port, put ":"
ip:port    192.168.0.100:80
Or use port 8080

**Comment by dragos-olaru** [comment]
python impulse.py --time 2000 --threads 150 --method SYN --target 198.168.0.100:80

**Comment by GTRacing65** [comment]
know it works thank you very much!

**Comment by dragos-olaru** [comment]
No problem! 👍
