### ISSUE TITLE
Python3 error

### ISSUE THREAD

**Issue by dragos-olaru** [LimerBoy/Impulse#51]
pkg install python3 python3-pip git -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3
E: Unable to locate package python3-pip

**Comment by LimerBoy** [comment]
Try: pkg update

**Comment by dragos-olaru** [comment]
I fixed it. Idk how but i deleted python trying to update it.

**Comment by dragos-olaru** [comment]
But i still can't install python3-pip

**Comment by LimerBoy** [comment]
Try pkg install python-pip
