### ISSUE TITLE
[!] Your device is not connected to the Internet

### ISSUE THREAD

**Issue by Zup1993** [LimerBoy/Impulse#56]
Thank you for your tools.
In use, I tested a host on the internal network, but the program popped up an error.[!] Your device is not connected to the Internet
How should I set it up？
<img width="753" alt="微信截图_20200826100402" src="https://user-images.githubusercontent.com/39846114/91246884-96812700-e783-11ea-8ccf-57ed304a2ed5.png">

**Comment by game-lover** [comment]
Are you connected to the network?

**Comment by LimerBoy** [comment]
1. Open Impulse/tools/ipTools.py in your text editor.
2. Line 102:
![image](https://user-images.githubusercontent.com/43149460/91416772-85561a00-e858-11ea-9ef6-a4c88c0455c1.png)
