### ISSUE TITLE
ZALYPA (((

### ISSUE THREAD

**Issue by maybephonker** [LimerBoy/Impulse#59]
:=== Critical error:
    MESSAGE: Failed import some modules.
    ERROR: No module named 'wget'
    :=== Python info:
    PYTHON VERSION: 3.8.5
    PYTHON BUILD: default, DATE: Jul 24 2020 12:30:25
    PYTHON COMPILER: Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489
    SCRIPT LOCATION: /data/data/com.termux/files/home/Impulse
    CURRENT LOCATION: /data/data/com.termux/files/home/Impulse
    :=== System info:
    SYSTEM: Linux
    RELEASE: 4.9.31
    VERSION: #1 SMP PREEMPT Tue Aug 18 14:41:28 IST 2020
    ARCHITECTURE: 32bit
    PROCESSOR:
    MACHINE: i686
    NODE: localhost
    TIME: Mon Sep  7 17:01:07 2020

**Comment by dragos-olaru** [comment]
pip3 install -r requirements.txt
