### ISSUE TITLE
Добавление сервисов для email спама

### ISSUE THREAD

**Issue by ghost** [LimerBoy/Impulse#61]
Привет!
Прошу добавить сервисы для email спама:
https://book.cyberyozh.com/ru/otpravka-anonimnyh-elektronnyh-pisem/

https://anonym-mail.5ymail.com/

А также Rambler почту, так как её регистрация возможна без подтверждения по номеру телефона...

**Comment by LimerBoy** [comment]
Сервисов для спама емейлами нету.
Спам проводиться с вашего ящика который вы сохранили в бомбере!
