### ISSUE TITLE
[Question] What theme and os you using, sir?

### ISSUE THREAD

**Issue by daeeros** [LimerBoy/Impulse#68]
Can yoy pls, what theme and os you using?

**Comment by LimerBoy** [comment]
OS Manjaro KDE
Icons: Papirus dark.
Theme: SweetKDE
Terminal: deepin-terminal

**Comment by daeeros** [comment]
> OS Manjaro KDE
> Icons: Papirus dark.
> Theme: SweetKDE
> Terminal: deepin-terminal

Ty :3
